logging:
    level:
        edu: debug
spring:
    ai:
        openai:
            api-key: ${OPEN_API_KEY}
            chat:
                options:
                    model: gpt-4
    application:
        name: openai-functions
        ninja:
            api-key: ${NINJA_API_KEY}
springdoc:
    api-docs:
        path: /api-docs
