logging:
  level:
    edu: debug
spring:
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-4
  application:
    name: openai-talk-to-text
springdoc:
  api-docs:
    path: /api-docs
